version: '3'
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5673:5673"
      - "15672:15672"
    networks:
      - config_test

networks:
  config_test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16